---
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.6
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      LOG_LEVEL: 'debug'
      LOG_FORMAT: 'text'
      PROMETHEUS_MONITORING_ENABLED: true
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
  prometheus:
    image: prom/prometheus:v3.0.1
    volumes:
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
       - "9090:9090"
  grafana:
    image: grafana/grafana:11.3.1
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
