apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: weaviate-app
spec:
  selector:
    matchLabels:
      app: weaviate
  podMetricsEndpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
      - weaviate
