---
services:
  weaviate-node-1:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.6
    volumes:
    - ./data-1:/var/lib/weaviate
    restart: on-failure:0
    environment:
      LOG_FORMAT: 'text'
      LOG_LEVEL: 'debug'
      PROMETHEUS_MONITORING_ENABLED: true
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'

      CLUSTER_HOSTNAME: 'node1'
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      RAFT_JOIN: 'node1,node2,node3'
      RAFT_BOOTSTRAP_EXPECT: 3

  weaviate-node-2:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8081'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.6
    volumes:
    - ./data-2:/var/lib/weaviate
    restart: on-failure:0
    environment:
      LOG_FORMAT: 'text'
      LOG_LEVEL: 'debug'
      PROMETHEUS_MONITORING_ENABLED: true
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'

      CLUSTER_HOSTNAME: 'node2'
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      CLUSTER_JOIN: 'weaviate-node-1:7100'
      RAFT_JOIN: 'node1,node2,node3'
      RAFT_BOOTSTRAP_EXPECT: 3

  weaviate-node-3:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8082'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.6
    volumes:
    - ./data-3:/var/lib/weaviate
    restart: on-failure:0
    environment:
      LOG_FORMAT: 'text'
      LOG_LEVEL: 'debug'
      PROMETHEUS_MONITORING_ENABLED: true
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'

      CLUSTER_HOSTNAME: 'node3'
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      CLUSTER_JOIN: 'weaviate-node-1:7100'
      RAFT_JOIN: 'node1,node2,node3'
      RAFT_BOOTSTRAP_EXPECT: 3

  prometheus:
    image: prom/prometheus:v3.0.1
    volumes:
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
       - "9090:9090"
  grafana:
    image: grafana/grafana:11.3.1
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning

  nginx:
    image: nginx:1-alpine
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
