---
services:
  weaviate-node-1:
    hostname: weaviate-node-1
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.3
    volumes:
    - ./data-1:/var/lib/weaviate
    restart: on-failure:0
    ports:
    - 6060:6060
    - 8071:8080
    - 50053:50051
    env_file: ".env"
    environment:
      CLUSTER_HOSTNAME: 'weaviate-node-1'
      GOMEMLIMIT: 2GiB
      QUERY_SLOW_LOG_ENABLED: true 
      QUERY_SLOW_LOG_THRESHOLD: 0ms
      GO_PROFILING_DISABLE: false
      GO_PROFILING_PORT: 6060

      LOG_FORMAT: 'text'
      LOG_LEVEL: 'debug'
      ASYNC_INDEXING: true,
      PROMETHEUS_MONITORING_ENABLED: true
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama,ref2vec-centroid,backup-filesystem,backup-s3'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'

      BACKUP_FILESYSTEM_PATH: '/tmp'

      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      RAFT_JOIN: 'weaviate-node-1,weaviate-node-2,weaviate-node-3'
      RAFT_BOOTSTRAP_EXPECT: 3

  weaviate-node-2:
    hostname: weaviate-node-2
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8081'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.3
    volumes:
    - ./data-2:/var/lib/weaviate
    restart: on-failure:0
    env_file: ".env"
    environment:
      CLUSTER_HOSTNAME: 'weaviate-node-2'
      GOMEMLIMIT: 2GiB

      QUERY_SLOW_LOG_ENABLED: true 
      QUERY_SLOW_LOG_THRESHOLD: 0ms
      LOG_FORMAT: 'text'
      LOG_LEVEL: 'debug'
      PROMETHEUS_MONITORING_ENABLED: true
      ASYNC_INDEXING: true,
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama,ref2vec-centroid,backup-filesystem,backup-s3'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'

      BACKUP_FILESYSTEM_PATH: '/tmp'

      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      CLUSTER_JOIN: 'weaviate-node-1:7100'
      RAFT_JOIN: 'weaviate-node-1,weaviate-node-2,weaviate-node-3'
      RAFT_BOOTSTRAP_EXPECT: 3

  weaviate-node-3:
    hostname: weaviate-node-3
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8082'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.3
    volumes:
    - ./data-3:/var/lib/weaviate
    restart: on-failure:0
    env_file: ".env"
    environment:
      CLUSTER_HOSTNAME: 'weaviate-node-3'
      GOMEMLIMIT: 2GiB

      QUERY_SLOW_LOG_ENABLED: true 
      QUERY_SLOW_LOG_THRESHOLD: 0ms
      LOG_FORMAT: 'text'
      LOG_LEVEL: 'debug'
      PROMETHEUS_MONITORING_ENABLED: true
      ASYNC_INDEXING: true,
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama,ref2vec-centroid,backup-filesystem,backup-s3'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'

      BACKUP_FILESYSTEM_PATH: '/tmp'

      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      CLUSTER_JOIN: 'weaviate-node-1:7100'
      RAFT_JOIN: 'weaviate-node-1,weaviate-node-2,weaviate-node-3'
      RAFT_BOOTSTRAP_EXPECT: 3

  prometheus:
    image: prom/prometheus:v3.0.1
    volumes:
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
       - "9090:9090"
  grafana:
    image: grafana/grafana:11.3.1
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file: ".env"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning

  nginx:
    image: nginx:1-alpine
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
